### ISSUE TITLE
[Feature Request] Add SypherEngine to Jitpack

### ISSUE THREAD

**Issue by YeffyCodeGit** [SypherEngine/SypherEngine#12]
Currently, SypherEngine is just...code. No one can use any parts of the engine, unless they build the whole engine from the source, which is probably not something anyone wants to do unless necessary.

**The Solution**
Publish SypherEngine on Maven Central, so that it can be installed by build tools.

**Alternative**
Use Jitpack, which is a popular and simpler alternative to Maven Central.

**Comment by AurumByte** [comment]
Hi there! and thanks for your interest in SypherEngine! As for your problem... well, SypherEngine is complete to some extent... but it still lacks enough basic features that are necessary in a game engine... like cameras, and basic collision detection. So I feel that i can't really release SypherEngine for build tools just yet... but once the features are done... will do :P

**Comment by YeffyCodeGit** [comment]
You can always create a snapshot build, which only people who want to test out whatever you have atm can use, and create a proper build when you feel sypher to be completed

**Comment by AurumByte** [comment]
Although I agree with you... I still have to say no. People can test yes... but reinventing the wheel for things that the Game Engine itself should handle is kinda annoying from a user point of view... also tests are lacking and I'd hate to upload the engine API without testing all of its current features

**Comment by YeffyCodeGit** [comment]
That's understandable, but do publish it somewhere once it's at a usable state! :D

**Comment by AurumByte** [comment]
will do! :)
