### ISSUE TITLE
Implement spotless code formatter

### ISSUE THREAD

**Issue by YeffyCodeGit** [SypherEngine/SypherEngine#33]
**Is your feature request related to a problem? Please describe.**
It can be difficult to keep a consistent code style, and i've already found more than one incident where the code style declared in the [CONTRIBUTING.md](https://github.com/SypherEngine/SypherEngine/blob/bcf113a69097258e67e5ebe71dd60349ec436354/CONTRIBUTING.md) has been broken.

**Describe the solution you'd like**
Implement https://github.com/diffplug/spotless to keep the code style consistent.

**Describe alternatives you've considered**
I haven't thought of any alternatives, but let me know if there are any other code formatters for Java, that you might prefer more.

**Comment by AurumByte** [comment]
Hi there! :wave:  

About the code style, you're absolutely right! It is inconsistent in places and keeping it consistent would make the engine easier to maintain, and keeps everything consistent. But before adding this, I wanted to release a few bug fixes, and to specify more cases for the code style in CONTRIBUTING.md file (such as for multiple arguments, long if statement conditions etc). 

Until then, if you're interested, you're more than welcome to get a PR going to tackle the issue. I'll pull in the changes and refactor them into the update too. :+1:

**Comment by YeffyCodeGit** [comment]
I'd be happy to PR, but i think I'll wait until add more cases, so I can get everything at once!
