### ISSUE TITLE
Gaming feature

### ISSUE THREAD

**Issue by ghost** [SypherEngine/SypherEngine#62]
Your engine is really nice, Could you maybe make it more beginner friendly, I'm new to jave ^^'

**Comment by 8BitAurum** [comment]
uh... Hello there! You seem to have come across the wrong repo, this isn't anything related to minecraft

**Comment by circleakash** [comment]
WHAT DO YOU MEAN NOT RELATED YOU SCAMMER!!!!!!!!! I PAID 20 BUCKS FOR THIS!!!! WRONG REPO??? THIS ISN'T ROBLOX ITS MINECRAFT YOU SAID MINECRAFT YOU CUNNING BASTARD!!!!

**Comment by ghost** [comment]
Wow, you seem really nice and helpful. Okay.
